name: Create Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Validate version and branch
        run: |
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          TAG_NAME=${{ github.ref_name }}
          if [[ "$BRANCH_NAME" == "main" && ! "$TAG_NAME" =~ ^v3\. ]]; then
            echo "Error: Tags on main branch must start with v3."
            exit 1
          # [TODO] Is it necessary to distribute v2.x?
          # elif [[ "$BRANCH_NAME" == "release/2.x" && ! "$TAG_NAME" =~ ^v2\. ]]; then
          #  echo "Error: Tags on release/2.x branch must start with v2."
          #  exit 1
          fi

  build:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Archive Repository
        run: zip -r release.zip . -x '.git/*' '.github/*' '.git*' './scripts/*'

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release.zip
          asset_name: release.zip
          asset_content_type: application/zip